### ISSUE TITLE
Addition of Local Storage (leave your suggestions here!)

### ISSUE THREAD

**Issue by W00nderer** [W00nderer/To-Do-List#4]
Would be nice if the tasks could be saved when refreshing the page. Please leave your suggestions here!

**Comment by alvarotorrestx** [comment]
Hey there, this can be done with local storage. I'd like to help. Assign me if you're ok with that 😄

**Comment by W00nderer** [comment]
> Hey there, this can be done with local storage. I'd like to help. Assign me if you're ok with that 😄

I appreciate your help! I think I assigned you to the issue, I hope it's working

**Comment by alvarotorrestx** [comment]
@W00nderer yes, you sure did! Thanks, I'll get started 👌

**Comment by W00nderer** [comment]
@alvarotorrestx  Thank you! The code looks good and the comments you left really help. Now I will be working on the Delete and Complete functions, and I would be happy to work with you on other issues if there are any :)

**Comment by alvarotorrestx** [comment]
@W00nderer awesome good luck and don't hesitate to reach out! 😊
